### PR TITLE
Feature/register

### PR DESCRIPTION
**Pull request by OR13**
This is currently blocked by https://github.com/transmute-industries/transmute-api/pull/1

### CODE REVIEW

**Comment by eolszewski** [comment]
In the future, we are to be very careful with capitalizations of folders. Git is not recognizing the difference between `Components/` and `components/` and did not pull things down correctly when I was working on a merge from master to my stream models branch. I can't even force a commit because there are files missing and git is pretty confused right now...

**Comment by eolszewski** [comment]
So, I think I resolved this with some weird git-fu, but it was pretty niche knowledge - we should try to avoid this in the future. But, I know how to resolve this if it comes up

**Comment by joshuacox** [comment]
I wonder if APFS is to blame for this one, I don't think git can tell the difference, a quick test in /tmp shows me that indeed git is seeing the difference on ext4:

```
   46 cd /tmp; mkdir new; cd new; git init
   47  mkdir Components
   48  mkdir components
   49  echo two > components/file
   50  echo three > Components/file
```

```
➜  new git:(master) ✗ git status 
On branch master

Initial commit

Changes to be committed:
  (use "git rm --cached <file>..." to unstage)

        new file:   Components/file
        new file:   components/file
```

**Comment by joshuacox** [comment]
Looks like by default APFS is insensitive by default:
https://developer.apple.com/library/content/documentation/FileManagement/Conceptual/APFS_Guide/FAQ/FAQ.html

**Comment by eolszewski** [comment]
This is good to know, I'm going to peek a bit more into this to make sure this won't destroy my computer if I enable case-sensitivity 👍

**Pull request merged**
