### PR TITLE
Feature/e-signer

### PR DESCRIPTION
**Pull request by eolszewski**

### CODE REVIEW

**Comment by OR13** [comment]
I'm taking ownership of this branch.

**Comment by OR13** [comment]
This branch has a passing build, but it has tangled our dashboard for events with the e-sign use case.

I seperated the demo into its own component, but there is a lot of cleanup work still left to do.

**Comment by OR13** [comment]
@eolszewski to review this.

**Comment by eolszewski** [comment]
Reviewing.

**Pull request merged**
