### PR TITLE
Fix bootstrap permission issue

### PR DESCRIPTION
**Pull request by ramilexe**
Running `bootstrap` as non-root user show error:

```npm WARN checkPermissions Missing write access to /usr/lib/node_modules
npm ERR! path /usr/lib/node_modules
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall access
npm ERR! Error: EACCES: permission denied, access '/usr/lib/node_modules'
npm ERR!  { Error: EACCES: permission denied, access '/usr/lib/node_modules'
npm ERR!   stack: 'Error: EACCES: permission denied, access \'/usr/lib/node_modules\'',
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/usr/lib/node_modules' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.
```

### CODE REVIEW

**Comment by OR13** [comment]
Seems that build is failing because root does not have npm in path.

**Comment by joshuacox** [comment]
This is because npm is already installed, and therefore bootstrap did not install node and npm using nvm as you already have npm and node, but you don't have access to your own /usr/lib/node_modules.  To get around this there are a few options:

1. use sudo with npm e.g. `sudo npm i`
1. `sudo chown -R $USER /usr/lib/node_modules`  which may or may not be appropriate if people other than you use this system.
1. install a version of node yourself using nvm or another node version manager.
1. or I could turn off the detection of an existing node/npm and merely force the nvm installation in bootstrap.

**Comment by joshuacox** [comment]
Also, this article details changing your node prefix to be `~/.npm-global`, 

https://docs.npmjs.com/getting-started/fixing-npm-permissions

I'm on the fence about 'fixing' this in bootstrap, my original opinion was that if someone already has node/npm installed then I will not touch it in the interest of not breaking their other node projects.  But this means many people who have system node installed, but have not set their node prefix to something they can actually write to, will have experience the same issue.

**Comment by OR13** [comment]
so I don't think `sudo npm i` is wise to do, sudo should not be needed if node is installed correctly.

I think its best to use a node version manager, or set prefix.

@ramilexe can you try the approach from the npm docs that is linked and report back if it does not resolve this issue?

In the past I have reinstalled node/npm to resolve this issue as the docs recommend.

**Comment by OR13** [comment]
See https://github.com/npm/npm/issues/19883 I don't want to be encouraging the use of sudo.

**Comment by joshuacox** [comment]
Closing here, feel free to re-open if you want me to take a second look.  But at this point in time we are going with the approach of testing the npm prefix, and if the user cannot write to that directory then error out with an explanation of the npm prefix and how to set it properly.

**Pull request closed without merging**
