### PR TITLE
Fix E-Signer Demo

### PR DESCRIPTION
**Pull request by OR13**
These changes support the macOS starting guide.

https://github.com/transmute-industries/transmute/wiki/macOS-guide

### CODE REVIEW

**Comment by eolszewski** [comment]
When running the app after setup.

screen shot 2018-07-11 at 1 10 50 pm

**Comment by eolszewski** [comment]
While working on a way to present this information to the user, I received the following when trying to ping ganache:

```
curl -k -X POST --data '{"jsonrpc":"2.0","method":"web3_clientVersion","params":[],"id":67}' https://ganache.transmute.minikube:30610/; echo
curl: (35) Unknown SSL protocol error in connection to ganache.transmute.minikube:-9847
```

Without SSL, I get:

```
curl -k -X POST --data '{"jsonrpc":"2.0","method":"web3_clientVersion","params":[],"id":67}' http://ganache.transmute.minikube:30610/; echo
{"id":67,"jsonrpc":"2.0","result":"EthereumJS TestRPC/v2.1.0/ethereum-js"}
```

**Comment by eolszewski** [comment]
And for some reason, this error is happening on the first time that an eventstore is created.

screen shot 2018-07-11 at 1 38 09 pm

**Comment by eolszewski** [comment]
https://github.com/transmute-industries/transmute/issues/178
https://github.com/transmute-industries/transmute/issues/179
https://github.com/transmute-industries/transmute/issues/180

**Comment by OR13** [comment]
@eolszewski the eventstore defect has been present for a while, and is unrelated to this changeset. the whole point of these changes is not to use ssl, so you should not be using ssl.

The user should tail the logs from their minikube pod to get the keys from ganache.

Something like:

```
kubectl logs $GANACHE_POD_NAME
```

The documentation for the E-Signer demo is here: 

https://github.com/transmute-industries/transmute/wiki/E-Signer-Demo

Maybe we should add documentation for using metamask and infura?

**Comment by OR13** [comment]
This guide goes along with these changes.

https://github.com/transmute-industries/transmute/wiki/E-Signer-on-Infura-With-MetaMask

I'm not going to finish the Infura documentation, as we are about to do a release, so it will be better to document as we go when we do that.

**Pull request merged**
